routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('register.reset');
Route::get('password/reset/','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('register','Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register','Auth\RegisterController@register');
Route::post('login','Auth\LoginController@login');
Route::get('login','Auth\LoginController@showLoginForm')->name('login');


Route::group(['middleware' => ['auth']], function () {
    Route::post('logout','Auth\LoginController@logout')->name('logout');
    Route::resource('koperasi','KoperasiController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('jenis_koperasi','JenisKoperasiController');
    Route::get('role','ManagementUserController@formRole')->name('role');
    Route::post('role','ManagementUserController@addRole');
    Route::get('user','ManagementUserController@allUsers')->name('user');
    Route::get('user/create','ManagementUserController@createUser')->name('user.create');
    Route::post('user','ManagementUserController@storeUser')->name('user.store');
    Route::delete('user/{id}','ManagementUserController@destroyUser')->name('user.destroy');
    Route::get('user/{id}/edit','ManagementUserController@editUser')->name('user.edit');
    Route::put('user/{id}','ManagementUserController@updateUser')->name('user.update');
    Route::get('file/create','FileController@createFileKoperasi');
    Route::post('file','FileController@storeFile')->name('file.store');
    Route::get('file/{id}','FileController@showFileKoperasi')->name('fileKoperasi.show');
    Route::delete('file/{id}','FileController@destroyFileKoperasi')->name('fileKoperasi.destroy');
    Route::get('file/{id}/edit','FileController@editFileKoperasi');
    Route::put('file/{id}','FileController@updateFileKoperasi');
});

app/Http/Controllers/JenisKoperasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use File;
use Auth;
use Image;
use App\JenisKoperasiModel;

class JenisKoperasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.jenisKoperasi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            if($request->hasfile('image'))
            {
                $image = $request->file('image');            
                $thumbnailImage = Image::make($image);            
                $originalPath = public_path().'/jenisImage/';
                $thumbnailImage->save($originalPath.time().$image->getClientOriginalName());
                $jenis = new JenisKoperasiModel;
                $jenis->users_id = Auth::user()->id;
                $jenis->nama = $request->input('nama');
                $jenis->image = time().$image->getClientOriginalName();
                $jenis->save();

                return redirect('koperasi')->with('success','Data Berhasil di Tambahkan');
            } else {
                $jenis = new JenisKoperasiModel;
                $jenis->users_id = Auth::user()->id;
                $jenis->nama = $request->input('nama');
                $jenis->image = 'default_image.jpg';
                $jenis->save();
                return redirect('koperasi')->with('success','Data Berhasil di Tambahkan');
            }
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $jenisKoperasi = JenisKoperasiModel::findOrFail($id);
        return view('admin.jenisKoperasi.edit',[     
            'jenisKoperasi' => $jenisKoperasi
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            if($request->hasFile('image'))
            {
                $image = $request->file('image');
                $thumbnailImage = Image::make($image);
                $originalPath = public_path().'/jenisImage/';
                $thumbnailImage->save($originalPath.time().$image->getClientOriginalName());
                $jenis = JenisKoperasiModel::findOrFail($id);
                $deletedImageOld = public_path().'/jenisImage/'.$jenis->image;
                File::delete($deletedImageOld);
                $jenis->users_id = Auth::user()->id;
                $jenis->nama = $request->input('nama');
                $jenis->image = time().$image->getClientOriginalName();
                $jenis->save();

                return redirect('koperasi')->with('success', 'Data Berhasil di Perbaharui');
            } else {
                $jenis = JenisKoperasiModel::findOrFail($id);                
                $jenis->users_id = Auth::user()->id;
                $jenis->nama = $request->input('nama');
                $jenis->save();
                return redirect('koperasi')->with('success', 'Data Berhasil di Perbaharui');
            }

        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $jenis = JenisKoperasiModel::findOrFail($id);
            if($jenis->image == "default_image.jpg")
            {                
                $jenis->delete();
            } else {
                $deleteImage = public_path()."/jenisImage/".$jenis->image;            
                File::delete($deleteImage);
                $jenis->delete();
            }
            return back()->with('success','Data Berhasil di Hapus');
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }
}

resources/views/admin/jenisKoperasi/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Jenis Koperasi
@endsection
@section('headerPage')
    Tambah Jenis Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('jenis_koperasi.store')}}" enctype="multipart/form-data">
    @csrf
        <div class="form-group">
            <label>Nama</label>
            <input type="name" class="form-control" name="nama" placeholder="Masukan Nama Jenis Kopeasi">
        </div>
        <div class="form-group m-form__group row">
                <label class="form-control-label col-sm-12">File Input</label>
                <div class="col-sm-12">
                    <div class="input-group file-input">
                        <input type="file" class="upload" name="image">
                        <input class="form-control" placeholder="No File Selected" type="text">
                        <span class="remove-file" style="display: none;"><i class="la la-times-circle"></i></span>
                        <div class="input-group-append">
                            <button type="button" class="btn btn-primary file-name"><i class="la la-file"></i></button>
                        </div>		
                    </div>
                </div>
            </div>        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/jenisKoperasi/edit.blade.php
@extends('layouts.app')
@section('title')
    Tambah Jenis Koperasi
@endsection
@section('headerPage')
    Tambah Jenis Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('jenis_koperasi.update',$jenisKoperasi->id)}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
        <div class="form-group">
            <label>Nama</label>
            <input type="text" name="nama" class="form-control" value="{{$jenisKoperasi->nama}}">            
        </div>
        <div class="form-group m-form__group row">
                <label class="form-control-label col-sm-12">File Input</label>
                <div class="col-sm-12">
                    <div class="input-group file-input">
                        <input type="file" class="upload" name="image">
                        <input class="form-control" placeholder="No File Selected" type="text">
                        <span class="remove-file" style="display: none;"><i class="la la-times-circle"></i></span>
                        <div class="input-group-append">
                            <button type="button" class="btn btn-primary file-name"><i class="la la-file"></i></button>
                        </div>		
                    </div>
                </div>
            </div>        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection