routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('register.reset');
Route::get('password/reset/','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('register','Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register','Auth\RegisterController@register');
Route::post('login','Auth\LoginController@login');
Route::get('login','Auth\LoginController@showLoginForm')->name('login');


Route::group(['middleware' => ['auth']], function () {
    Route::post('logout','Auth\LoginController@logout')->name('logout');
    Route::resource('koperasi','KoperasiController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('jenis_koperasi','JenisKoperasiController');
    Route::get('role','ManagementUserController@formRole')->name('role');
    Route::post('role','ManagementUserController@addRole');
    Route::get('user','ManagementUserController@allUsers')->name('user');
    Route::get('user/create','ManagementUserController@createUser')->name('user.create');
    Route::post('user','ManagementUserController@storeUser')->name('user.store');
    Route::delete('user/{id}','ManagementUserController@destroyUser')->name('user.destroy');
    Route::get('user/{id}/edit','ManagementUserController@editUser')->name('user.edit');
    Route::put('user/{id}','ManagementUserController@updateUser')->name('user.update');
    Route::get('file/create','FileController@createFileKoperasi');
    Route::post('file','FileController@storeFile')->name('file.store');
    Route::get('file/{id}','FileController@showFileKoperasi')->name('fileKoperasi.show');
    Route::delete('file/{id}','FileController@destroyFileKoperasi')->name('fileKoperasi.destroy');
    Route::get('file/{id}/edit','FileController@editFileKoperasi');
    Route::put('file/{id}','FileController@updateFileKoperasi');
});

app/Http/Controllers/KoperasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\KoperasiModel;
use App\JenisKoperasiModel;
use App\RekapFileModel;
use Auth;
use File;
use App\Http\Requests\KoperasiRequestStore;

class KoperasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function uniqueFilename($path, $name, $ext) {
	
        $output = $name;
        $basename = basename($name, '.' . $ext);
        $i = 2;
        
        while(File::exists($path . '/' . $output)) {
            $output = $basename . $i . '.' . $ext;
            $i ++;
        }
        
        return $output;
        
    }    
    public function index()
    {
        $jenisKoperasi = JenisKoperasiModel::all();
        return view('admin.koperasi.index',['jenisKoperasi' => $jenisKoperasi]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jenisKoperasi = JenisKoperasiModel::all();
        return view('admin.koperasi.create',['jenisKoperasi' => $jenisKoperasi]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KoperasiRequestStore $request)
    {
        try {            
            $koperasi = new KoperasiModel;
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');
            $koperasi->biaya_hosting = $request->input('biaya_hosting');
            $koperasi->pic_teknik = $request->input('pic_teknik');
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');
            $koperasi->save();
            
            return redirect('koperasi')->with('success','Data Berhasil di Masukan');
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jenisKoperasi = JenisKoperasiModel::with(['koperasi','users'])->findOrFail($id);        
        return view('admin.koperasi.show',['jenisKoperasi' => $jenisKoperasi]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $koperasi = KoperasiModel::with(['jenis','rekap_file'])->findOrFail($id);
        $jenis = JenisKoperasiModel::all();        
        return view('admin.koperasi.edit',[
            'koperasi' => $koperasi,
            'jenis' => $jenis
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KoperasiRequestStore $request, $id)
    {
        try {
            $koperasi = KoperasiModel::with('jenis')->findOrFail($id);
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');
            $koperasi->biaya_hosting = $request->input('biaya_hosting');
            $koperasi->pic_teknik = $request->input('pic_teknik');    
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');

            $koperasi->save();

            return redirect('koperasi/'.$koperasi->jenis->id)->with('success', 'Data Berhasil di Perbaharui');         
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $koperasi = KoperasiModel::with('rekap_file')->findOrFail($id);
            foreach($koperasi->rekap_file as $value)
            {
                $path = public_path()."/files/".$value->nama;
                File::delete($path);
            }            
            $koperasi->delete();

            return back()->with('success','Data Berhasil di Hapus');
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }
}

resources/views/admin/koperasi/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Koperasi
@endsection
@section('headerPage')
    Tambah Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('koperasi.store')}}" enctype="multipart/form-data">
    @csrf
        <div class="form-group">
            <label>Jenis Koperasi</label>
            <select name="jenis_id" class="form-control" required>                
                @foreach ($jenisKoperasi as $item)
                <option value="{{$item->id}}">{{$item->nama}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Nomor SPK</label>
            <input type="name" class="form-control" name="nomor_spk" placeholder="Masukan Nomor SPK" required>
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal SPK</label>                
            <div class="input-group m-input-group">
                <input type="text" name="tgl_spk" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" required>
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Nama Institusi</label>
            <input type="name" class="form-control" name="nama_institusi" placeholder="Masukan Nama Institusi" required>
        </div>
        <div class="form-group">
            <label>Nama Ketua</label>
            <input type="name" class="form-control" name="nama_ketua" placeholder="Masukan Nama Ketua" required>
        </div>        
        <div class="form-group">
            <label for="">Alamat</label>
            <textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Masukan Alamat"></textarea>
        </div>
        <div class="form-group">
            <label>Jumlah Anggota</label>
            <input type="number" class="form-control" name="jml_anggota" placeholder="Masukan Jumlah Anggota">
        </div>
        <div class="form-group">
            <label>Biaya Hosting</label>
            <input type="number" class="form-control" name="biaya_hosting" placeholder="Masukan Biaya Hosting">
        </div>
        <div class="form-group">
            <label>Pic Teknik</label>
            <input type="text" class="form-control" name="pic_teknik" placeholder="Masukan Pic Teknik">
        </div>
        <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="number" class="form-control" name="no_telp" placeholder="Masukan Nomor Telepon" min="11">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" placeholder="Masukan Email">
        </div>
        <div class="form-group">
            <label>URL</label>
            <input type="url" class="form-control" name="url" placeholder="Masukan URL">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal Setup</label>
            <div class="input-group m-input-group">
                <input type="text" name="tgl_setup" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Harga Aplikasi</label>
            <input type="number" class="form-control" name="harga_aplikasi" placeholder="Masukan Harga Aplikasi">
        </div>
        <div class="form-group">
            <label>History</label>
            <input type="text" class="form-control" name="history" placeholder="Masukan History">
        </div>
        <div class="form-group">
            <label>Status Pembayaran</label>
            <input type="text" class="form-control" name="status_pembayaran" placeholder="Masukan Status Pembayaran">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/koperasi/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Koperasi
@endsection
@section('headerPage')
    Edit Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('koperasi.update',$koperasi->id)}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
        <div class="form-group">
            <label>Jenis Koperasi</label>
            <select name="jenis_id" class="form-control">                
                @foreach ($jenis as $item)
                <option value="{{$item->id}}" {{ $item->id == $koperasi->jenis->id ? "selected" : "" }}>{{$item->nama}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Nomor SPK</label>
            <input type="name" class="form-control" name="nomor_spk" placeholder="Masukan Nomor SPK" value="{{ $koperasi->nomor_spk }}">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal SPK</label>                
            <div class="input-group m-input-group">
                <input type="text" name="tgl_spk" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" value="{{ $koperasi->tgl_spk }}">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Nama Institusi</label>
            <input type="name" class="form-control" name="nama_institusi" placeholder="Masukan Nama Institusi" value="{{ $koperasi->nama_institusi }}">
        </div>
        <div class="form-group">
            <label>Nama Ketua</label>
            <input type="name" class="form-control" name="nama_ketua" placeholder="Masukan Nama Ketua" value="{{ $koperasi->nama_ketua }}">
        </div>        
        <div class="form-group">
            <label for="">Alamat</label>
            <textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Masukan Alamat">{{ $koperasi->alamat }}</textarea>
        </div>
        <div class="form-group">
            <label>Jumlah Anggota</label>
            <input type="number" class="form-control" name="jml_anggota" placeholder="Masukan Jumlah Anggota" value="{{ $koperasi->jml_anggota }}">
        </div>
        <div class="form-group">
            <label>Biaya Hosting</label>
            <input type="number" class="form-control" name="biaya_hosting" placeholder="Masukan Biaya Hosting" value="{{ $koperasi->biaya_hosting }}">
        </div>
        <div class="form-group">
            <label>Pic Teknik</label>
            <input type="text" class="form-control" name="pic_teknik" placeholder="Masukan Pic Teknik" value="{{ $koperasi->pic_teknik }}">
        </div>
        <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="name" class="form-control" name="no_telp" placeholder="Masukan Nomor Telepon" value="{{ $koperasi->no_telp }}">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" placeholder="Masukan Email" value="{{ $koperasi->email }}">
        </div>
        <div class="form-group">
            <label>URL</label>
            <input type="url" class="form-control" name="url" placeholder="Masukan URL" value="{{ $koperasi->url }}">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal Setup</label>
            <div class="input-group m-input-group">
                <input type="text" name="tgl_setup" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" value="{{ $koperasi->tgl_setup }}">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Harga Aplikasi</label>
            <input type="number" class="form-control" name="harga_aplikasi" placeholder="Masukan Harga Aplikasi" value="{{ $koperasi->harga_aplikasi }}">
        </div>
        <div class="form-group">
            <label>History</label>
            <input type="text" class="form-control" name="history" placeholder="Masukan History" value="{{ $koperasi->history }}">
        </div>
        <div class="form-group">
            <label>Status Pembayaran</label>
            <input type="text" class="form-control" name="status_pembayaran" placeholder="Masukan Status Pembayaran" value="{{ $koperasi->status_pembayaran }}">
        </div>
    </form>        

@endsection

resources/views/admin/koperasi/index.blade.php
@extends('layouts.app')
@section('title')
    Daftar Semua Kategori
@endsection
@section('headerPage')
    Daftar Semua Kategori
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="la la-list"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Daftar Semua Kategori
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ url('jenis_koperasi/create') }}" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air">
                        <span>
                            <i class="la la-plus"></i>
                            <span>Tambah Jenis</span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item">
                    <a href="{{ url('koperasi/create') }}" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--pill m-btn--air">
                        <span>
                            <i class="la la-plus"></i>
                            <span>Tambah Koperasi</span>
                        </span>
                    </a>
                </li>        

            </ul>
        </div>
        
    </div>
    <div class="m-portlet__body no-pedding">
        @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('danger'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                {{ session()->get('danger') }}
        </div>
        @endif
        <div class="list-section">                
            @forelse ($jenisKoperasi as $item)
            
            <div class="list-section__item">
                <div class="section__content image-box">
					<div class="section__widget">
						<div class="section__img">
							<img src="{{asset('jenisImage/'.$item->image)}}" class="imageThumb">
						</div>
					</div>
                    <div class="section__desc">
                        <h5 class="section__title">{{ $item->nama }}</h5>
                        <div class="section__info">

                            <div class="section__info__item sm-text">
                                <span class="info__label">Posted By :</span>
                                <a href="" class="info__detail m-link">{{ $item->users->name }}</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section__action">
                    <div class="list__section__action">
						<a href="{{ url('koperasi/'.$item->id) }}"
                            class="btn m-btn btn-info btn-sm  m-btn--icon m-btn--square m-btn--air icon-only">
                            <span>
                                <i class="la la-list"></i>
                                <span>Lihat Koperasi</span>
                            </span>
                        </a>
                        <a href="{{ url('jenis_koperasi/'.$item->id.'/edit') }}" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--air icon-only">
                            <span>
                                <i class="la la-pencil"></i>
                                <span>Edit Kategori</span>
                            </span>
                        </a>
                        <a href="#" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
                            <span>
                                <i class="la la-eye"></i>
                                <span>Lihat Koperasi</span>
                            </span>
                        </a>
                        <a href="javascript:void(0);" onclick="$(this).find('form').submit();"
                            class="btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5">
                            <span>
                                <i class="la la-trash"></i>
                                <span>Delete Kategori</span>
                            </span>
                            <form action="{{ route('jenis_koperasi.destroy', $item->id) }}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                            </form>
                        </a>
                    </div>
                </div>
            </div>
            @empty
            <div class="m-portlet__body">
                <p>Data Kosong</p>
            </div>
            @endforelse            
        </div>
    </div>
</div>
@endsection

resources/views/admin/koperasi/show.blade.php
@extends('layouts.app')
@section('title')
  Daftar Semua Koperasi {{$jenisKoperasi->nama}}
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <span class="m-portlet__head-icon">
          <i class="la la-list"></i>
        </span>
        <h3 class="m-portlet__head-text">
          Daftar Semua Koperasi {{$jenisKoperasi->nama}}
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body no-pedding">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('success') }}
    </div>
    @endif
    @if(session()->has('danger'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('danger') }}
    </div>
    @endif
    <div class="list-section">
      @forelse ($jenisKoperasi->koperasi as $item) 
      <div class="list-section__item">
        <div class="section__content image-box">
          <div class="section__desc">
            <h5 class="section__title">{{ $item->nama_institusi }}</h5>
            <div class="section__info">
              <div class="section__info__item sm-text">
                <span class="info__label">Posted By :</span>
                <a href="" class="info__detail m-link">{{ $item->users->name }}</a>
              </div>
            </div>
          </div>
        </div>
        <div class="section__action">
          <div class="list__section__action">
            <a href="{{ url('koperasi/'.$item->id.'/edit')}}" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--air icon-only">
              <span>
                <i class="la la-pencil"></i>
                <span>Edit Koperasi</span>
              </span>
            </a>
            <a href="{{ url('file/'.$item->id) }}" class="btn m-btn btn-info btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
              <span>
                <i class="la la-file"></i>
                <span>Management File</span>
              </span>
            </a>            
            <a href="#" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
              <span>
                <i class="la la-eye"></i>
                <span>Profil Koperasi</span>
              </span>
            </a>
            <a href="javascript:void(0);" onclick="$(this).find('form').submit();" class="btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5">
              <span>
                <i class="la la-trash"></i>
                <span>Delete Koperasi</span>                
              </span>
              <form action="{{ route('koperasi.destroy', $item->id) }}" method="post">
                @csrf
                @method('DELETE')
              </form>
            </a>
          </div>
        </div>
      </div>
      @empty
      <div class="m-portlet__body">
        <p>Kosong</p>
      </div>        
      @endforelse            
    </div>
  </div>
</div>
@endsection